import { z } from 'zod';
import { diagnose } from './diagnostics.js';
import { Comparisons } from './comparisons.js';

export function registerUnifiedTools(server, kernel) {
  const provider = z.enum([...kernel.providers.keys()]);
  const session_id = z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,63}$/).optional().describe('Stable caller-chosen session name. Different names use independent tabs and can generate concurrently; reuse the same name for follow-ups. Omit for the legacy tab.');
  const comparisons = new Comparisons(kernel);
  const tool = (name, description, schema, handler) => server.registerTool(name, { description, inputSchema: schema }, async (input, extra) => {
    try { return { content: [{ type: 'text', text: JSON.stringify(await handler(input, extra.signal), null, 2) }] }; }
    catch (error) { return { isError: true, content: [{ type: 'text', text: JSON.stringify({ code: error.code || 'CHAT_ERROR', error: error.message }) }] }; }
  });
  const run = (id, method, args, signal, readOnly = false, sessionId) => kernel.run(id, (browser) => browser[method](...args), { signal, readOnly, sessionId, conversationChanged: ['newChat', 'selectHistory'].includes(method), name: `chat_${method}` });
  tool('chat_compare', 'Send the same question to 2..6 explicitly authorized provider/model targets in fresh conversations. Discover exact names with chat_models first. Providers run independently; models on one provider run sequentially. Reuse identical input and request_id to resume unsent targets. Each answer stays separate; no automatic judge or synthesis.', { request_id: z.string().min(1).max(128), prompt: z.string().min(1), targets: z.array(z.object({ provider, model: z.string().min(1) })).min(2).max(6), timeoutMs: z.number().int().min(1000).max(300000).default(30000) }, (i, signal) => comparisons.run(i, { signal }));
  tool('chat_compare_result', 'Observe comparison children without sending or changing models. Returns each target response, task state and recovery guidance separately.', { comparison_id: z.string() }, (i, signal) => comparisons.result(i.comparison_id, { signal }));
  tool('chat_providers', 'List installed providers and their supported capabilities. No browser access.', {}, async () => ({ providers: [...kernel.providers.values()].map(({ id, capabilities }) => ({ id, capabilities })) }));
  tool('chat_doctor', 'Inspect local executable, runtime and task-journal health. Does not open a browser or verify sign-in. Report excludes paths, conversation URLs, task IDs, responses and raw errors.', { provider: provider.optional() }, (i) => diagnose(kernel, i.provider ? [i.provider] : undefined));
  tool('chat_status', 'Read the selected session page and local managed-task state. Optional ChatGPT include_messages returns the currently rendered user/assistant text for read-only recovery inspection; it neither acknowledges nor releases a task.', { provider, session_id, include_messages: z.boolean().default(false) }, async (i, signal) => {
    if (i.include_messages && i.provider !== 'chatgpt') throw Object.assign(new Error('include_messages currently supports ChatGPT only.'), { code: 'INVALID_ARGUMENT' });
    const status = await run(i.provider, 'status', [], signal, true, i.session_id);
    const observed = i.include_messages ? await run(i.provider, 'getLatestResponse', [{ includeTranscript: false }], signal, true, i.session_id) : undefined;
    if (observed) observed.rendered_messages = await run(i.provider, 'renderedConversationMessages', [{ includeRawText: true }], signal, true, i.session_id);
    return { ...status, ...(observed ? { observed } : {}), session_id: i.session_id || null, ...await kernel.list(i.provider, 1) };
  });
  tool('chat_models', 'List names actually available on the selected provider session. Model names are provider-specific.', { provider, session_id }, (i, s) => run(i.provider, 'listModels', [], s, false, i.session_id));
  tool('chat_select_model', 'Select and verify an exact available model name. Gemini optionally sets and verifies its separate Extended thinking toggle before sending.', { provider, session_id, model: z.string().min(1), extended_thinking: z.boolean().optional() }, (i, s) => {
    if (i.extended_thinking !== undefined && i.provider !== 'gemini') throw Object.assign(new Error('extended_thinking is supported only for Gemini.'), { code: 'INVALID_ARGUMENT' });
    return run(i.provider, 'selectModel', [i.model, { extended_thinking: i.extended_thinking }], s, false, i.session_id);
  });
  tool('chat_new', 'Create a conversation in the selected session. Other sessions are unaffected. Tasks and drafts in this session prevent unsafe switching.', { provider, session_id }, (i, s) => run(i.provider, 'newChat', [], s, false, i.session_id));
  tool('chat_send', 'Submit once and return a durable task_id. Distinct session_id values allow concurrent answers on independent tabs. Reuse the SAME request_id and content after a timeout; replay never resends. Files require user authorization. Optional ChatGPT answer_tier (e.g. Pro) is selected and verified before sending; web_search enables native web search. Rate limits remain shared.', { provider, session_id, request_id: z.string().min(1).max(128), prompt: z.string().min(1), files: z.array(z.string().min(1)).max(10).default([]), model: z.string().min(1).optional(), answer_tier: z.string().min(1).optional(), web_search: z.boolean().default(false) }, (i, signal) => kernel.send(i, { signal }));
  tool('chat_result', 'Read/resume a durable task without sending. Named sessions restore the saved conversation. Completed answers are cached unless refresh=true explicitly revalidates the latest task in that session. For an unbound uncertain send, supply an observed conversation_url; its user turn must match before binding. Never resend uncertain work.', { task_id: z.string(), wait: z.boolean().default(false), refresh: z.boolean().default(false), conversation_url: z.string().url().optional(), timeoutMs: z.number().int().min(1000).max(300000).default(30000) }, (i, signal) => kernel.result(i.task_id, { ...i, signal }));
  tool('chat_cancel', 'Cancel ONLY the generation belonging to this task, after verifying conversation and prompt identity. A completed task stays completed. If cancellation cannot be confirmed, the reservation remains.', { task_id: z.string() }, (i, signal) => kernel.read(i.task_id, { signal, cancel: true }));
  tool('chat_retry', 'Click the original completed answer retry control once after the caller reviews a refusal and has user authorization. Currently Gemini only. Keeps the same task and prompt; never sends a duplicate user message. Repeated calls recover the single attempt without clicking again. Continue with chat_result; no retry for running, uncertain, superseded or rate-limited work.', { task_id: z.string() }, (i, signal) => kernel.retry(i.task_id, { signal }));
  tool('chat_tasks', 'List local task metadata without opening a browser or exposing prompt text. Supports state filtering and offset pagination; results include total and next_offset.', { provider, limit: z.number().int().min(1).max(100).default(20), offset: z.number().int().min(0).default(0), state: z.enum(['preparing', 'submitting', 'submitted', 'running', 'uncertain', 'completed', 'cancelled', 'failed', 'abandoned']).optional() }, (i) => kernel.list(i.provider, i.limit, i));
  tool('chat_abandon', 'Explicit recovery after inspecting an uncertain task: release local tracking only when the original page is idle. Does not undo delivery or clear drafts. Requires user authorization; never call automatically after a timeout. The same request_id will still never resend.', { task_id: z.string(), confirm: z.literal(true) }, (i, signal) => kernel.abandon(i.task_id, { confirm: i.confirm, signal }));
  tool('chat_history', 'List provider conversation history; inspect the returned scope/completeness information.', { provider, session_id, query: z.string().default(''), limit: z.number().int().min(1).max(50).default(20) }, (i, s) => run(i.provider, 'listHistory', [{ query: i.query, limit: i.limit }], s, false, i.session_id));
  tool('chat_open', 'Open a provider conversation URL in the selected session. Refuses to switch away from its managed task.', { provider, session_id, url: z.string().url() }, (i, s) => run(i.provider, 'selectHistory', [i.provider === 'chatgpt' ? { url: i.url } : i.url], s, false, i.session_id));
  tool('chat_archive', 'Explicitly export the selected session conversation to local Markdown. Provider-specific history completeness is preserved.', { provider, session_id }, (i, s) => run(i.provider, 'archiveConversation', [], s, false, i.session_id));
}
